### ISSUE TITLE
Post records with incorrect/malformed fields?

### ISSUE THREAD

**Issue by habedi** [sotorrent/db-scripts#11]
Hi,

I found this record in the ```Posts table``` (in ```Posts.xml.gz```), the value for ```Id``` is incorrectly set to ```22990644``` while the right ```Id``` seems to have to be ```22990633```;  also, ```ParentId``` and ```CreationDate``` look incorrect too;

```xml
 <row Id="22990644" PostTypeId="2" ParentId="22989404" CreationDate="2014-04-10T14:melhosseiny's answer.&lt;/p&gt;&#xA;" OwnerUserId="3166768" LastEditorUserId="1033581" LastEditDate="2018-05-01T03:54:03.087" LastActivityDate="2018-05-01T03:54:03.087" Title="Installing Django Error" Tags="&lt;python&gt;&lt;django&gt;&lt;cmd&gt;" AnswerCount="1" CommentCount="7" />
```

I guess there maybe a few other incorrect post records but I am not sure how it could affect the integrity of the data.

**Comment by sbaltes** [comment]
Thanks for reporting this.
Did you check whether the same issue is also present in the XML file from the official data dump?
You can download it using:

`wget https://archive.org/download/stackexchange/stackoverflow.com-Posts.7z`

If the issue is also present in that file, please report this on [Stack Exchange Meta](https://meta.stackexchange.com/). If the record is only malformed in the _SOTorrent_ version of the file, please let me know and I'm going to look into it.

**Comment by habedi** [comment]
Hi,

Sorry for the late reply, my internet connexion is kinda slow so it took a little bit of time before I could download ```stackoverflow.com-Posts.7z```.
I searched for the record with ```Id = 22990644``` using ```grep``` in ```Posts.xml``` in both files, The two files are ```Posts.xml.gz``` with ```md5sum = ff7cbf0c93cf8efabdd9512324d8a30b``` and ```stackoverflow.com-Posts.7z``` with ```md5sum = 3cb0cd663d5b244873b43be4462e7f76```. Here are the outputs:

```Bash
# Posts.xml from https://archive.org/download/stackexchange/stackoverflow.com-Posts.7z
$ grep 22990644 stackoverflow.com-Posts/Posts.xml

  <row Id="22990644" PostTypeId="2" ParentId="22989404" CreationDate="2014-04-10T14:15:11.527" Score="2" Body="&lt;p&gt;According to &lt;a href=&quot;https://stackoverflow.com/questions/22979151/improper-advertising-identifier-idfa-usage&quot;&gt;this post&lt;/a&gt;, the only way to go back to start again is to upload an empty Xcode project (without any reference to IDFA) using the same bundle ID and, after it has been uploaded, reject the binary.&lt;/p&gt;&#xA;&#xA;&lt;p&gt;You can then restart the process, mark IDFA as used, and upload the correct project.&lt;/p&gt;&#xA;&#xA;&lt;p&gt;However, notice that if you do not use IDFA for actually displaying ads, your app could be rejected by Apple.&lt;/p&gt;&#xA;" OwnerUserId="67397" LastEditorUserId="-1" LastEditDate="2017-05-23T11:44:52.287" LastActivityDate="2014-04-10T14:15:11.527" CommentCount="0" />

grep: input lines truncated - result questionable
```

```Bash
# Posts.xml from SOTorrent (Version 2018-12-09)
$ grep 22990644 extracted\Posts.xml

  <row Id="22990644" PostTypeId="2" ParentId="22989404" CreationDate="2014-04-10T14:melhosseiny's answer.&lt;/p&gt;&#xA;" OwnerUserId="3166768" LastEditorUserId="1033581" LastEditDate="2018-05-01T03:54:03.087" LastActivityDate="2018-05-01T03:54:03.087" Title="Installing Django Error" Tags="&lt;python&gt;&lt;django&gt;&lt;cmd&gt;" AnswerCount="1" CommentCount="7" />

grep: input lines truncated - result questionable
```
It seems the record is correct in the original file. One weird thing that I have noticed is that the modification date file attribute for ```Posts.xml``` after extraction from both ```stackoverflow.com-Posts.7z``` and ```Posts.xml.gz``` is identical (it is set to ```Dec  2 17:03```).

**Comment by sbaltes** [comment]
Are you sure that you did not modify the XML file from the _SOTorrent_ dataset after downloading it?
When I extract `stackoverflow.com-Posts.7z` and `Posts.xml.gz` and calculate the MD5 hash values, they are the same:

```
$ md5sum Posts_Dump.xml
e055eb46b7909e746d185b324fd131ad *Posts_Dump.xml

$ md5sum Posts_SOTorrent.xml
e055eb46b7909e746d185b324fd131ad *Posts_SOTorrent.xml
```

A grep search also yields the same result for that particular row:

```
$ grep '<row Id="22990644"' Posts_Dump.xml
  <row Id="22990644" PostTypeId="2" ParentId="22989404" CreationDate="2014-04-10T14:15:11.527" Score="2" Body="&lt;p&gt;According to &lt;a href=&quot;https://stackoverflow.com/questions/22979151/improper-advertising-identifier-idfa-usage&quot;&gt;this post&lt;/a&gt;, the only way to go back to start again is to upload an empty Xcode project (without any reference to IDFA) using the same bundle ID and, after it has been uploaded, reject the binary.&lt;/p&gt;&#xA;&#xA;&lt;p&gt;You can then restart the process, mark IDFA as used, and upload the correct project.&lt;/p&gt;&#xA;&#xA;&lt;p&gt;However, notice that if you do not use IDFA for actually displaying ads, your app could be rejected by Apple.&lt;/p&gt;&#xA;" OwnerUserId="67397" LastEditorUserId="-1" LastEditDate="2017-05-23T11:44:52.287" LastActivityDate="2014-04-10T14:15:11.527" CommentCount="0" />

$ grep '<row Id="22990644"' Posts_SOTorrent.xml
  <row Id="22990644" PostTypeId="2" ParentId="22989404" CreationDate="2014-04-10T14:15:11.527" Score="2" Body="&lt;p&gt;According to &lt;a href=&quot;https://stackoverflow.com/questions/22979151/improper-advertising-identifier-idfa-usage&quot;&gt;this post&lt;/a&gt;, the only way to go back to start again is to upload an empty Xcode project (without any reference to IDFA) using the same bundle ID and, after it has been uploaded, reject the binary.&lt;/p&gt;&#xA;&#xA;&lt;p&gt;You can then restart the process, mark IDFA as used, and upload the correct project.&lt;/p&gt;&#xA;&#xA;&lt;p&gt;However, notice that if you do not use IDFA for actually displaying ads, your app could be rejected by Apple.&lt;/p&gt;&#xA;" OwnerUserId="67397" LastEditorUserId="-1" LastEditDate="2017-05-23T11:44:52.287" LastActivityDate="2014-04-10T14:15:11.527" CommentCount="0" />
```

Could you calculate the MD5 hash values of the extracted XML files and compare them with the hash values posted above?

**Comment by habedi** [comment]
As a matter of fact, the first thing I did was to check SHA1 checksum for ```Posts.xml``` files.

For me they were not the same:

```Bash
# Posts.xml from https://archive.org/download/stackexchange/stackoverflow.com-Posts.7z
$ sha1sum.exe stackoverflow.com-Posts\Posts.xml
d52678a7575b74393c59b5c0cc2716e1e9140e96
```

```Bash
# Posts.xml from SOTorrent (Version 2018-12-09)
$ sha1sum.exe extracted\Posts.xml
a3834512b466d3928ff74714e35ec5564389e624
```

I can't send you the MD5 digests right away, if you still need them I could post them in a few hours though.

**Comment by sbaltes** [comment]
I re-downloaded the files from Zenodo and Archive, but the MD5 hash is still the same:

```
$ md5sum Posts_Zenodo.xml
e055eb46b7909e746d185b324fd131ad *Posts_Zenodo.xml

$ md5sum Posts_Archive.xml
e055eb46b7909e746d185b324fd131ad *Posts_Archive.xml
```

I also calculated the SHA1 hash, which is also equal:

```
$ sha1sum Posts_Zenodo.xml
e8adafeb43fcc20facb4a35e2be8e5e8dbbb2af6 *Posts_Zenodo.xml

$ sha1sum Posts_Archive.xml
e8adafeb43fcc20facb4a35e2be8e5e8dbbb2af6 *Posts_Archive.xml
```

So to me, this currently looks like a problem on your end.
Please let me know if there is anything else I can do.

**Comment by habedi** [comment]
I re-extracted the ```Posts.tar.gz```, and the this time the SHA1 hash for the both files matches. I think there maybe a problem with my hard drive's filesystem or something similar that resulted in data corruption in the first place. So, I think this issue is closed. 
Sorry for the inconvenience and thank you very for your rime and considerations.
