### ISSUE TITLE
Decompose SO posts into code and text blocks

### ISSUE THREAD

**Issue by effat** [sotorrent/db-scripts#13]
The MSR 2018 [paper](https://arxiv.org/pdf/1803.07311.pdf) section 4 describes decomposing a SO post into text blocks and code blocks. But I could not find the (class `PostVersionHistoryTest` [11]) following reference 11 in this [link](https://github.com/sotorrent/posthistory-extractor).

I  need to decompose the Body of a SO post (Posts Table of Figure 2) into code and text blocks for one of my projects. My data is saved in a `.csv` file. 

Your paper describes nicely how to extract code blocks from a SO post:
1)  SO Markdown (indented by 4 spaces),
2) code fencing Markdown (enclosed by three backticks), SO stack
3) snippets (enclosed by `<!--begin/end snippet-->`), stack snippet
4) language tags (prepended by `<!--language:...-->`),
5) HTML codetags (enclosed by `<pre><code>`),
6) and HTML script tags (enclosed by `<script>`).

Could you please provide the source code to decompose a SO post Body into code and text blocks? It would be really appreciating.

**Comment by sbaltes** [comment]
You'll find the code here:

https://github.com/sotorrent/posthistory-extractor/blob/30f0b55e65b856c4cf5962f844f680c5500b7908/src/org/sotorrent/posthistoryextractor/history/PostHistory.java#L235

And the tests here:

https://github.com/sotorrent/posthistory-extractor/blob/master/tests/PostBlockExtractionTest.java

Please be aware that you need to use the markdown source (table `PostHistory`) and not the parsed HTML content (table `Posts`).

Alternatively, you could just retrieve the blocks from table `PostBlockVersion`. You can use column `PostHistoryId ` to select only the most recent post version:

```
SELECT *
FROM PostBlockVersion pbv
WHERE PostHistoryId = (
  SELECT MAX(PostHistoryId)
  FROM PostVersion pv
  WHERE pv.PostId = pbv.PostId
)
```
