### ISSUE TITLE
README.md out of date on zenodo

### ISSUE THREAD

**Issue by CosmosAtlas** [sotorrent/db-scripts#14]
Hi,

I noticed that the README.md file on zenodo seems to contain out of date information on sql file names. It currently does not describe the available data on zenodo.

Thanks!

**Comment by sbaltes** [comment]
Thanks for reporting this, the file names of the SQL scripts should now be in sync with the README file. This change will be visible on Zenodo after the next release, because I cannot update files in existing dataset versions.
