### ISSUE TITLE
SOTorrent latest release on Zenodo

### ISSUE THREAD

**Issue by Alfusainey** [sotorrent/db-scripts#18]
is the date in the version name of the latest release of the SOTorrent dataset on Zenodo  a typo? it  was uploaded on Zenodo on Jan 25, 2020 but  the name  is `Version 2019-01-24`. On Google Bigquery it is `2020-01-24`

**Comment by sbaltes** [comment]
Thanks, this was indeed a typo.
Should be fixed now.
