### ISSUE TITLE
Some rows of PostReferenceGH Table does not look valid !

### ISSUE THREAD

**Issue by JafarAkhondali** [sotorrent/db-scripts#2]
I was inspecting `PostReferenceGH` at Google Big Query and first page of preview was:
![image](https://user-images.githubusercontent.com/11364402/47595915-a6652f80-d98f-11e8-89d0-34c727b04fa9.png)

SOUrl  doesn't look right on this page. For example:
[this file in gh](https://raw.githubusercontent.com/GEKONavsat/FreeIMU/master/libraries/FreeIMU/debug/decode_float.py) has this link:
`# http://stackoverflow.com/questions/1592158/python-convert-hex-to-float/1...`
But the extracted link in  PostReferenceGH is: 
`http://stackoverflow.com/a/1`

I dont know how many rows has been affected by similar problem and i think regexes in `./bigquery/1_extract_so_references.sql` caused this bug.

Thanks for your effort. :+1:

**Comment by sbaltes** [comment]
Thanks for reporting this. I will look into it later today.

**Comment by sbaltes** [comment]
I created [Java versions](https://github.com/sotorrent/util/blob/419b0a4a455a305b88e9b296b3522a7c3a4bb6a6/src/org/sotorrent/util/URL.java#L50) of the corresponding regular expressions and added different [test cases](https://github.com/sotorrent/util/blob/419b0a4a455a305b88e9b296b3522a7c3a4bb6a6/tests/URLTest.java#L45), including the source code line you mentioned above.

I'm now stricter regarding the answer links and rather treat links as question links if they are somehow malformed. In the next release of the dataset, this will be fixed:

![2018-10-27 19_27_19-window](https://user-images.githubusercontent.com/10498957/47607312-7add5600-da1e-11e8-925f-6c8ac49f0abb.png)

I also updated the [changelog](https://github.com/sotorrent/db-scripts/blob/master/CHANGELOG.md).

**Comment by CosmosAtlas** [comment]
I just ran the same query on the newest dataset (Mar. 2019), the problem still exists.

![temp](https://user-images.githubusercontent.com/5738747/55211104-feaf9000-51c0-11e9-9094-738c0b904241.png)
