### ISSUE TITLE
Script to import data from .sql files

### ISSUE THREAD

**Issue by monjurmorshed793** [sotorrent/db-scripts#22]
I have downloaded data from the Zenodo site. All the files are of .sql type. A script may be added to import those sql files.

**Comment by sbaltes** [comment]
You can use this script: https://github.com/sotorrent/db-scripts/blob/master/sotorrent/load_sotorrent.sh (you also need the SQL scripts used in that Bash script).
It will be part of the next release of the dataset, the script in the current release contains a bug, but Zenodo doesn't like when you update files in existing datasets.
Please re-open this issue if you have trouble importing the dataset.
