### ISSUE TITLE
sotorrent20_03.GHCommits missing

### ISSUE THREAD

**Issue by Alfusainey** [sotorrent/db-scripts#23]
The  `sotorrent20_03` version on Zenodo does not include the `GHCommits` table. Was this intentional?

**Comment by sbaltes** [comment]
Interesting. Maybe the upload to Zenodo failed. I'll host the file temporarily on Google Drive and post a link here, while I'll contact Zenodo to add the missing file.

**Comment by sbaltes** [comment]
Here's the link: https://drive.google.com/file/d/1DqaAx0JMdFvBIzk-figoX0lpnnf6M2Wv/view?usp=sharing

**Comment by Alfusainey** [comment]
> Here's the link: https://drive.google.com/file/d/1DqaAx0JMdFvBIzk-figoX0lpnnf6M2Wv/view?usp=sharing

thanks @sbaltes. I loaded the file and got 3,608 records. does that sound right?

**Comment by sbaltes** [comment]
That's strange. When I execute 

`wc -l GHCommits.csv`

I get the following:

`195210 GHCommits.csv`

Thus 195,209 entries (header row excluded), which is the same count as on BigQuery.
Maybe there's an issue with the line endings on your end?

**Comment by Alfusainey** [comment]
> That's strange. When I execute
> 
> `wc -l GHCommits.csv`
> 
> I get the following:
> 
> `195210 GHCommits.csv`
> 
> Thus 195,209 entries (header row excluded), which is the same count as on BigQuery.
> Maybe there's an issue with the line endings on your end?

Thanks, it works now. The problem was that i included the `Id` field name in the field list:

```SQL
(Id, CommitId, Repo, RepoOwner, RepoName, PostId, @CommentId, SOUrl, GHUrl)
SET CommentId = nullif(@CommentId, '');
```

And removing the `Id` field solved it

**Comment by sbaltes** [comment]
I see. Thanks for letting me know!
The Zenodo dataset is now updated as well.
