### ISSUE TITLE
Discussion Forum for sotorrent

### ISSUE THREAD

**Issue by Alfusainey** [sotorrent/db-scripts#24]
@sbaltes I have two questions:

(1) How about having a dedicated discussion forum (Gitter, GitHub discussion, etc) for sotorrent? The idea is to bring the sotorrent user community under one forum to ask rapid/quick questions regarding the dataset without the need for creating GH issues.  Do you think this kind of make sense?

(2) If I select the latest version of a code snippet (i.e MostRecentVersion=True and PostBlockTypeId=2 and LineCount >= 10), what  does `PredCount` means for the latest code snippet version? Does it mean a count of all the **modified** code snippet versions that exist prior to the latest version? Or does the count include cases were a latest version is exactly the same as  the prior versions?

E.g if we take the ff. version chains, were each version is modified: 
(1) `rootid->v2->v3->latestVersion`. In this case, PredCount=3 and
(2) `rootid->latestVersion`. In this case PredCount=1

An example were the versions are not modified (i.e PredEqual IS NOT NULL OR PredEqual != 0):
(1) `rootid->v2->v3->latestVersion`. In this case, PredCount=3 and
(2) `rootid->latestVersion`. In this case PredCount=1

**Comment by sbaltes** [comment]
Sorry for the late reply.

(1) This is a great idea, but I don't even have time to publish new versions of the dataset, so I won't have time to quickly respond in such a forum. 

(2) `PredCount` is the number of potential predecessors (with same similarity), of which one is selected according to the matching strategy (see MSR 2018 paper for details). Here's the property in the code: https://github.com/sotorrent/posthistory-extractor/blob/93ac77e7bcd3617b87bbec3a34e1ce40a801a47f/src/org/sotorrent/posthistoryextractor/blocks/PostBlockVersion.java#L67

**Comment by Alfusainey** [comment]
> Sorry for the late reply.
> 
> (1) This is a great idea, but I don't even have time to publish new versions of the dataset, so I won't have time to quickly respond in such a forum.
> 
> (2) `PredCount` is the number of potential predecessors (with same similarity), of which one is selected according to the matching strategy (see MSR 2018 paper for details). Here's the property in the code: https://github.com/sotorrent/posthistory-extractor/blob/93ac77e7bcd3617b87bbec3a34e1ce40a801a47f/src/org/sotorrent/posthistoryextractor/blocks/PostBlockVersion.java#L67

Thanks @sbaltes. I think the sotorrent community should help out in publishing new versions of the dataset. This is something I am willing to do. Is there a documentation available for how this can be done? I think once the dataset is prepared, you can then do the publishing to Bigquery and zenodo

**Comment by sbaltes** [comment]
Yes, that's exactly what I'm working on :-)
Since creating the dataset from an SO dump and the BigQuery GitHub dataset requires a quite powerful local setup (e.g., 64 GB RAM) besides the parts that already run in the cloud, I want to completely move the pipeline to the cloud so that everyone can run it, also without powerful local hardware.
I'd be happy to do a handover with you once documentation and infrastructure are available.
Just give me a ping end of February. I hope to have finished the work until then.

**Comment by Alfusainey** [comment]
awesome! sure, i will do that

**Comment by zl1n** [comment]
Hi @sbaltes, I am also interested in becoming a member of the SOTorrent community. Any updates on the documentation and infrastructure you mentioned in this thread ;) ?

**Comment by sbaltes** [comment]
Hi @zl1n and @Alfusainey,
I currently unfortunately don't have much capacity to dedicate to working on SOTorrent.
One challenge is integrating [this code](https://github.com/sotorrent/posthistory-extractor) into [this pipeline](https://github.com/sotorrent/pipeline).
I thought it's a good exercise to re-implement the logic in Python, but in hindsight it might have been better to stick to Java...
Anyways, in case you're interested in helping with that task, please let me know.
Best regards,
Sebastian
