### ISSUE TITLE
Question about PostTags table

### ISSUE THREAD

**Issue by JafarAkhondali** [sotorrent/db-scripts#4]
Hi,
We are a group of students in Shiraz university supervised by Professor Ashkan Sami and our hardware is kinda limited so we have to optimize our queries as much as possible.
Currently there is a `tags` column in `Posts` table and have a type of `NVARCHAR` and tags are wrapped in tags column like < TAGNAME >. I was confused that why there is not a many-to-many relationship for `tags` and `posts` tables so i tried extracting tags using this query:

```

SELECT 
	id as PostsPostIds,
  TagName
  TagId
	FROM `sotorrent-org.2018_03_28.Posts` as Posts
  
	INNER JOIN (SELECT 
			Id as TagId,
			TagName
		FROM `sotorrent-org.2018_03_28.Tags` ) as TagsTbl
	On Posts.tags LIKE CONCAT('<%', TagsTbl.TagName, '%>')
  WHERE Posts.PostTypeId = 1
```

And then [found out](https://meta.stackexchange.com/questions/2677/database-schema-documentation-for-the-public-data-dump-and-sede) there is already a table named `PostTags` which is not included in so-torrent dataset.

May i know the reason ?

**Comment by sbaltes** [comment]
The table `PostTags` is available in the [Stack Exchange Data Explorer](https://data.stackexchange.com/), but not in the [data dump](https://archive.org/download/stackexchange) that *SOTorrent* uses. You could ask on Stack Exchange Meta why this table is not included in the dump. I'm very sorry that I currently can't provide any further support in this matter. I'll mark this as a possible enhancement. Maybe I can create such a table for a later release of *SOTorrent*.

**Comment by JafarAkhondali** [comment]
Thank you so much! I didn't know it's not available in data dump.
Using above query it would be easy to create this table but it needs lot of computations (currently running on Google Bigquery for more than an hour).
Thanks for your help, It's Stack Exhange fault :sweat_smile:

**Comment by sbaltes** [comment]
Table available starting with version 2020-03-15.
